import { createRequire } from "node:module";
import assert from "node:assert/strict";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || "playwright");
const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || "chrome" });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
let confirms=0, calls=0;
const snapshot={schema_version:2,text:"袁记云饺，五图",facts:{store_name:"袁记云饺"},sources:{},assets:[],show_price:false,show_store_name:true,style:"appetite",provider:"qwen",gaps:[],ready:true,project_changes:[],render_mode:"illustration",messages:Array.from({length:20},(_,i)=>({role:i%2?"assistant":"user",content:i%2?"会用品牌氛围做一套连续五图。":"袁记云饺，五图"}))};
const review={creation_id:"smoke-creation",revision:1,status:"READY_TO_CONFIRM",snapshot_hash:"a".repeat(64),snapshot};
await page.route("**/api/v1/**", async route=>{
 calls++;
 const url=new URL(route.request().url()), p=url.pathname, method=route.request().method();
 let body={};
 if(p.endsWith("/projects")&&method==="POST")body={project_id:"smoke-project"};
 else if(p.endsWith("/assets"))body=[];
 else if(p.endsWith("/creations")&&method==="POST")body={creation_id:"smoke-creation",revision:0,status:"DRAFT",snapshot:null,snapshot_hash:""};
 else if(p.endsWith("/intake-runs")||p.endsWith("/review"))body=review;
 else if(p.endsWith("/confirm")){confirms++;body={task_id:"smoke-task"};}
 else if(p.endsWith("/pause"))body={id:"smoke-task",status:"NEEDS_USER",progress:8,result:{}};
 else if(p.includes("/tasks/"))body={id:"smoke-task",status:"RUNNING",progress:8,result:{}};
 await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(body),headers:{"access-control-allow-origin":"*"}});
});
try{
 await page.goto("http://127.0.0.1:3011/");
 await page.getByRole("heading",{name:"今天，想为门店做什么图？"}).waitFor();
 assert.equal(await page.locator(".quickAssetRail").count(),0);
 const input=page.getByRole("textbox",{name:"创作需求"});
 await input.fill("袁记云饺，五图");
 await page.getByRole("button",{name:"创作",exact:true}).click();
 assert.equal(await page.locator(".quickAssetRail").count(),1);
 await page.getByRole("tab",{name:"一键生图",exact:true}).click();
 assert.equal(await page.getByRole("textbox",{name:"创作需求"}).inputValue(),"袁记云饺，五图");
 const card=page.getByRole("button",{name:"添加照片",exact:true});
 const before=await page.locator(".studioComposer").boundingBox(); await card.hover(); await page.waitForTimeout(220);
 assert(before.y < 380, "welcome composer should not be vertically centered with excessive whitespace");
 assert(!(await input.getAttribute("placeholder")).includes("袁记"));
 const after=await page.locator(".studioComposer").boundingBox(); assert.deepEqual(after,before);
 await page.locator('input[type="file"]').last().setInputFiles({name:"smoke-photo.png",mimeType:"image/png",buffer:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aE6kAAAAASUVORK5CYII=","base64")});
 await page.getByRole("button",{name:"查看 1 张照片"}).hover();
 await page.getByRole("button",{name:"移除 smoke-photo.png",exact:true}).waitFor();
 assert.deepEqual(await page.locator(".studioComposer").boundingBox(),before,"photos and expansion must not increase composer height");
 assert.equal(await page.locator(".studioUploadCard .studioStackImage").count(),1);
 await page.screenshot({path:"/tmp/tuanhui-v091-photos.png"});
 await page.waitForTimeout(600);
 // A focused control must not pin a mouse-opened photo panel on screen.
 await page.getByRole("button",{name:"移除 smoke-photo.png",exact:true}).focus();
 await page.mouse.move(1300,100);
 assert.equal(await page.locator(".studioPhotoPopover").isVisible(),false);
 await page.getByRole("button",{name:"查看 1 张照片"}).hover();
 const removeStyle=await page.getByRole("button",{name:"移除 smoke-photo.png",exact:true}).evaluate(el=>({background:getComputedStyle(el).backgroundColor, icon:getComputedStyle(el,"::after").width}));
 assert.equal(removeStyle.background,"rgba(0, 0, 0, 0)");
 assert.equal(removeStyle.icon,"12px");
 await page.getByRole("button",{name:"预览 smoke-photo.png",exact:true}).hover();
 await page.getByRole("button",{name:"移除 smoke-photo.png",exact:true}).click();
 assert.equal(await page.locator(".studioPhotoGrid .referenceThumbnail").count(),0);
 const files=[1,2,3,4].map(i=>({name:`stack-${i}.png`,mimeType:"image/png",buffer:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aE6kAAAAASUVORK5CYII=","base64")}));
 await page.locator('input[type="file"]').last().setInputFiles(files);
 await page.getByRole("button",{name:"查看 4 张照片"}).hover();
 assert.equal(await page.locator(".studioStackImage").count(),3);
 assert.deepEqual(await page.locator(".studioComposer").boundingBox(),before);
 await page.getByRole("button",{name:"收起照片"}).click();
 assert.equal(await page.locator(".studioPhotoPopover").isVisible(),false);
 await page.setViewportSize({width:375,height:812});
 await page.waitForTimeout(500);
 await page.mouse.move(350,10);
 await page.getByRole("button",{name:"查看 4 张照片"}).focus();
 await page.keyboard.press("Enter");
 await page.getByRole("region",{name:"本次照片"}).waitFor();
 const pop=await page.locator(".studioPhotoPopover").boundingBox();
 assert(pop.x>=0 && pop.x+pop.width<=375 && pop.y>=0);
 await page.screenshot({path:"/tmp/tuanhui-v091-mobile-photos.png"});
 await page.keyboard.press("Escape");
 assert.equal(await page.locator(".studioPhotoPopover").isVisible(),false);
 await page.keyboard.press("Enter");
 for(const file of files) await page.getByRole("button",{name:`移除 ${file.name}`,exact:true}).click();
 await page.setViewportSize({width:1440,height:960});
 await page.screenshot({path:"/tmp/tuanhui-v09-desktop.png"});
 await page.getByRole("button",{name:"开始生成",exact:true}).click();
 await page.getByRole("dialog").waitFor();assert.equal(calls,0);
 await page.getByRole("button",{name:"同意并开始",exact:true}).click();
 await page.getByRole("heading",{name:"正在生成整张长图"}).waitFor();
 assert.equal(confirms,1);
 const bounds=await page.locator(".studioComposer").boundingBox(); assert(bounds.y+bounds.height<=960); assert(bounds.y+bounds.height>900); assert.equal(await page.evaluate(()=>scrollY),0);
 assert(await page.locator(".studioMessages").evaluate(el=>el.scrollHeight>el.clientHeight));
 await page.screenshot({path:"/tmp/tuanhui-v09-chat.png"});
 await page.getByRole("button",{name:"停止生成",exact:true}).click();
 await page.getByText("已停止，需求和素材已保留。需要重新生成时请开始下一次创作。").waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.waitForTimeout(300);
 const mobile=await page.locator(".studioComposer").boundingBox(); assert(mobile.y+mobile.height<=844);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:"/tmp/tuanhui-v09-mobile.png"});
 await page.setViewportSize({width:375,height:812}); await page.waitForTimeout(250);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.emulateMedia({reducedMotion:"reduce"});
 assert.equal(await card.evaluate(el=>getComputedStyle(el).transform),"none");
 console.log("PASS: home / hover stability / mode preservation / authorization / auto-confirm once / 20-message bounded layout / pause / mobile.");
}finally{await browser.close();}
